# wrangler.toml
name = "thrivequest"
compatibility_date = "2025-12-04"
pages_build_output_dir = ".svelte-kit/cloudflare"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "thrivequest"
database_id = "3b154a25-a5bc-41a6-a45c-31528c7cc69b"
